tcpcon:
	gcc tcpclient.c -o tcpclient
	gcc tcpserver_con.c -o tcpservercon

tcpiter:
	gcc tcpclient.c -o tcpclient
	gcc tcpserver_iter.c -o tcpserveriter

udp:
	gcc udpclient.c -o udpclient
	gcc udpserver.c -o udpserver

clean-tcpclient:
	rm tcpclient

clean-tcpcon:
	rm tcpservercon

clean-tcpiter:
	rm tcpserveriter

clean-udp:
	rm udpclient udpserver