all:
	gcc hamming.c -o hamming
	gcc checksum.c -o checksum

hamming:
	gcc hamming.c -o hamming

checksum:
	gcc checksum.c -o checksum

clean-all:
	rm hamming
	rm checksum

clean-hamming:
	rm hamming

clean-checksum:
	rm checksum